baseurl = "http://peakbook.github.io/"
title = "peakbook's weblog"
copyright = "Copyleft (É”) peakbook All rights reversed."

[author]
    name = "peakbook"
    twitter = "peakbook"
    github = "peakbook"
    gaID = "UA-60161276-1"
